version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  maria_db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: afa_db
      MYSQL_USER: server
      MYSQL_PASSWORD: Password
      MYSQL_ROOT_PASSWORD: Password